import JSZip from "jszip";
import { saveAs } from "file-saver";

export interface GeneratedFile {
  path: string;
  content: string;
}

export async function generateAndDownloadConfigs(role: string, recommendation: any) {
  const zip = new JSZip();

  // 1. Cursor Rules
  const cursorRules = `# AI Onboard - ${role} Best Practices

You are an expert ${role} using the latest 2026 AI tooling.
Always think step-by-step. Use LangGraph for complex tasks.
Prioritize clarity and maintainable code.`;

  zip.file(".cursor/rules/ai-onboard.md", cursorRules);

  // 2. GitHub Actions - AI Setup
  const githubAction = `name: AI Tooling Setup
on: [push, pull_request]

jobs:
  ai-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup AI Tools
        run: |
          echo "Setting up Cursor + Groq + Polygon CLI..."
          # Add more setup here
`;

  zip.file(".github/workflows/ai-tooling-setup.yml", githubAction);

  // 3. .env.example
  zip.file(".env.example", `GROQ_API_KEY=your_groq_key_here
NEXT_PUBLIC_SUPABASE_URL=...
# Add other tools...
`);

  // 4. Polygon Setup (for Blockchain role)
  if (role.toLowerCase().includes("blockchain")) {
    const polygonReadme = `# Polygon Agent CLI Setup

\`\`\`bash
polygonalabs login
polygonalabs wallet create
polygonalabs tools list
# Start building on Polygon!
\`\`\`
`;
    zip.file("POLYGON-SETUP.md", polygonReadme);
  }

  // 5. README.md with recommendations
  const readme = `# AI Onboarding for ${role}

${recommendation.skillPath ? recommendation.skillPath.map((s: string, i: number) => `${i+1}. ${s}`).join('\n') : ''}

Generated by AI Onboard — ${new Date().toISOString()}
`;

  zip.file("README-AI-ONBOARD.md", readme);

  // Generate and download
  const blob = await zip.generateAsync({ type: "blob" });
  saveAs(blob, `ai-onboard-${role.toLowerCase().replace(/\s+/g, '-')}.zip`);
}
